### ISSUE TITLE
Can't get this to compile

### ISSUE THREAD

**Issue by sykhro** [yellows8/ctr-nandmount#2]
I want to edit a couple emuNAND system savedata; I managed to xor the image and extract it, but I can't open any of the archives in which the .dat files are stored.
For example, \data[ID]\sysdata\0002009f\ should contain the Friend List savedata.
The folder contains a file with the name '00000000' and no extension. 
I've been told that this tool takes care of that, so I installed a Debian VM (I'm using Windows). However, I can't get this to compile. I've already installed gcc, pkg-config & fuse. 
When I run 'make' from the terminal I get this:

Package fuse was not found in the pkg-config search path.
Perhaps you should add the directory containing `fuse.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fuse' found

I tried doing echo $PKG_CONFIG_PATH in a terminal with root but it returns an empty line. 
How can I solve this?

**Comment by yellows8** [comment]
Roughly the same way as building anything using fuse I guess.

**Comment by sykhro** [comment]
solved, I didn't have pkg-config installed
